repos:
  - repo: local
    hooks:
      - id: ormolu
        name: ormolu
        entry: ormolu --mode check
        language: system
        files: '\.hs$'
        types: [file]
      - id: hlint
        name: hlint
        entry: hlint
        language: system
        files: '\.hs$'
        types: [file]