name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Setup Nix Cache
      uses: cachix/cachix-action@v12
      with:
        name: forketyfork
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      continue-on-error: true
        
    - name: Build and Test All Problems
      run: |
        nix develop --command bash -c "
          cabal update
          cabal test
        "
        
    - name: Check Code Style
      run: |
        nix develop --command bash -c "
          echo 'Checking code style with hlint...'
          if ! hlint src/Problem*.hs test/; then
            echo 'HLint found issues. Please fix them.'
            exit 1
          fi
          
          echo 'Checking formatting with ormolu...'
          for file in src/Problem*.hs test/*.hs; do
            if [ -f \"\$file\" ]; then
              if ! ormolu --mode check \"\$file\"; then
                echo \"Error: \$file has formatting issues\"
                exit 1
              fi
            fi
          done
          echo 'All style checks passed!'
        "
